export const actionsIds = {
  // App
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  // User & Auth
  GET_AUTH_STATUS: 'GET_AUTH_STATUS',
  AUTH_USER_LOADED: 'AUTH_USER_LOADED',
  AUTH_USER_ERROR: 'AUTH_USER_ERROR',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_ERROR: 'SIGN_IN_USER_ERROR',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  // User Profile
  CREATE_UPDATE_PROFILE_SUCCESS: 'CREATE_UPDATE_PROFILE_SUCCESS',
  CREATE_UPDATE_PROFILE_ERROR: 'CREATE_UPDATE_PROFILE_ERROR',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
  CLEAR_USER_PROFILE: 'CLEAR_USER_PROFILE',
  DELETE_USER_PROFILE: 'DELETE_USER_PROFILE',
  // ACTIVITIES
  CREATE_NEW_ACTIVITY: 'CREATE_NEW_ACTIVITY',
  GET_USER_ACTIVITIES: 'GET_USER_ACTIVITIES',
  GET_ACTIVITY_BY_ID: 'GET_ACTIVITY_BY_ID',
  DELETE_ACTIVITY_BY_ID: 'DELETE_ACTIVITY_BY_ID',
};
