export const actionsIds = {
  // App
  SET_ALERT: 'SET_ALERT',
  // User & Auth
  GET_AUTH_STATUS: 'GET_AUTH_STATUS',
  AUTH_USER_LOADED: 'AUTH_USER_LOADED',
  AUTH_USER_ERROR: 'AUTH_USER_ERROR',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_ERROR: 'SIGN_IN_USER_ERROR',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  // User Profile
  CREATE_UPDATE_USER_PROFILE: 'CREATE_UPDATE_USER_PROFILE',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  DELETE_USER_PROFILE: 'DELETE_USER_PROFILE',
  // Records
  CREATE_NEW_RECORD: 'CREATE_NEW_RECORD',
  GET_USER_RECORDS: 'GET_USER_RECORDS',
  GET_RECORD_BY_ID: 'GET_RECORD_BY_ID',
  DELETE_RECORD_BY_ID: 'DELETE_RECORD_BY_ID',
};
