export const actionsIds = {
  // App
  SET_ALERT: 'SET_ALERT',
  // User & Auth
  GET_AUTH_STATUS: 'GET_AUTH_STATUS',
  REGISTER_USER: 'REGISTER_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  // User Profile
  CREATE_UPDATE_USER_PROFILE: 'CREATE_UPDATE_USER_PROFILE',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  DELETE_USER_PROFILE: 'DELETE_USER_PROFILE',
  // Records
  CREATE_NEW_RECORD: 'CREATE_NEW_RECORD',
  GET_USER_RECORDS: 'GET_USER_RECORDS',
  GET_RECORD_BY_ID: 'GET_RECORD_BY_ID',
  DELETE_RECORD_BY_ID: 'DELETE_RECORD_BY_ID',
};
